### ISSUE TITLE
Project Todo List

### ISSUE THREAD

**Issue by proudmuslim-dev** [proudmuslim-dev/proudmuslim.tech#3]
Anything that needs to be done for the documentation will be located here. Please take a look at this list if you're planning on contributing.

 - [ ] Organize client migration lists (follow the [hyperium guides](https://github.com/proudmuslim-dev/proudmuslim.tech/blob/main/src/client-migration/hyperium.md)' format),
 - [ ] Grammar and spell checking on all files.
 - [ ] Update the [forge intro](https://github.com/proudmuslim-dev/proudmuslim.tech/tree/main/src/forge-intro) documents - this has to be done ourselves, as luna would prefer to keep the lists separate.

**Comment by MatthewTGM** [comment]
Do you still need help with these or are they a WIP?
